summary: XML-based font configuration library
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-28-aarch64/releases/download/2025.01.24/libfontconfig-2.15.0-android-28-arm64-v8a.release.tar.xz
bin-sha: b154105f14aa425a56579c75ab8db1d6f89ca0dda1361a9e5e522bf171a889df
