summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-android-28-aarch64/releases/download/2025.01.24/pkg-config-0.29.2-android-28-arm64-v8a.release.tar.xz
bin-sha: 93ad05e7b9f990a482d169bc0535dfa7397abfb32ab82fbbea1f10dcfdbbe26a
